spring:
  lifecycle.timeout-per-shutdown-ohase: 20s #default 30s
  application:
    name: spring_in_action

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comments

management:
  endpoints:
    web:
      base-path: /manage #default path start with actuator/**
      exposure:
        include: "*" #all metrics
        exclude: threaddump, heapdump #exluded metrics, default empty

server:
  shutdown: graceful

logging:
  file:
    path: /var/logs/
    file: StreetFood.log
  level:
    root: WARN
    org.springframework.security: DEBUG