spring:
  application:
    name: spring_in_action

  thymeleaf: false #template caching, don`t need in developing
  datasource:
    url: jdbc:h2:mem:streetFood
    username: sa
    password:
    name: streetFood
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: create

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comments

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

logging:
  level:
    root: DEBUG