spring:
  application:
    name: spring_in_action

  thymeleaf: false #template caching, don`t need in developing
  datasource:
    url: jdbc:h2:mem:streetFood
    username: sa
    password:
    name: streetFood
    generate-unique-name: false

  jpa:
    hibernate:
      ddl-auto: create

  data:
    mongodb:
      host: localhost
      port: 27017
      database: comments

logging:
  logging:
    file:
      path: /var/logs/
      file: StreetFood.log
  level:
    root: DEBUG